### ISSUE TITLE
1.7.4.4 Package

### ISSUE THREAD

**Issue by abrenner85** [netoffice/NetOffice-NuGet#7]
Hallo,
I'm glad there's new package on NuGet. We upgraded our project, but we still see the NetOffice 1.7.3?
How can we get the 1.7.4.4?

NetOffice writes: NetOffice Core.Initialize() NO Version:1.7.3.0 DeepLevel:True

**Comment by toyman** [comment]
Same here - all NetOffice packages presented in NuGet as 1.7.4.4 version are in fact previous 1.7.3.0 version.

**Comment by matteshe** [comment]
You need to take NetOfficeFw for up to date packages

Am 3. Juli 2018 14:53:10 MESZ schrieb toyman <notifications@github.com>:

**Comment by erikaleblanc88** [comment]
Hi @abrenner85, the version 1.7.4.4 is the correct NuGet package version for the latest version of the source code.
