### ISSUE TITLE
How to open word and save as pdf?

### ISSUE THREAD

**Issue by KakiLiang** [netoffice/NetOffice-NuGet#8]
How to use it? any document?

**Comment by erikaleblanc88** [comment]
@KakiLiang The issues of this repo are for reporting bugs and feature requests for the NuGet packages. For general questions on how to use NetOffice, please post on [Stackoverflow](https://stackoverflow.com/questions/tagged/netoffice): https://stackoverflow.com/questions/tagged/netoffice
